config/routes.rb
Elevate::Application.routes.draw do
 
  root :to =>  "pages#home"

  match '/benefits' => 'pages#platform', :via => [:get]
  match '/how_it_works' => 'pages#program', :via => [:get]
 

 resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :company, :email, :name, :phone

  validates_presence_of :email
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  	@contact = Contact.new
  end

  def create
  	@contact = Contact.new(params[:contact])
    @name = params[:contact][:name]
    @company = params[:contact][:company]
    @email = params[:contact][:email]
    @phone = params[:contact][:phone]
    
  	if @contact.save
      ContactMailer.notify_sales(@name, @company, @email, @phone).deliver
  	  redirect_to new_contact_path, :notice => "Thanks for contacting us! We'll be in touch shortly."
  	else
  		render new_contact_path
  		flash[:notice] = "Oops. Please enter the correct information and try again."
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


  def platform
  end

  def program
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<% content_for :head do %>
  <title>Email Marketing Automation for Clients - Contact Us | Elevate</title>
<% end %>
<div class="container-fluid contact_header">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>We Work With B2B Companies of All Sizes</h1>
    </div>
  </div>
</div>


<div class="container-fluid contact_section">

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <h3>You're in good company</h3>
      <p>Contact us today and we'll show you how you can identify upsell and cross-sell opportunities among your existing clients.
      </p>
      <%= image_tag 'contact_logos.png' %>
    </div>

    <div class="col-md-4 contact_form_area">
      <%= render 'layouts/messages' %>
        <%= form_for :contact, url: contacts_path, html: { class: "form_horizontal contact_form well"} do |f| %>
          <%= f.label :name, class: 'form_label' %>
          <%= f.text_field :name %><br />

          <%= f.label :email, class: 'form_label,' %>
          <%= f.text_field :email %><br />

          <%= f.label :phone, class: 'form_label' %>
          <%= f.text_field :phone %><br />

          <%= f.label :company, class: 'form_label' %>
          <%= f.text_field :company %><br />
    

          <span class="contact_button"><%= f.submit 'Request Details', class: 'btn btn-large btn-primary button_text'  %></span>
        <% end %>

    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid footer_width">
    <div class="row">
    
      <div class="col-md-3 col-md-offset-1">
        <h2>We're Hiring!</h2>
        <p>Elevate is always looking for talented people to join our growing team. Send us an email with a bit about yourself and let's talk.</p><br />
        <p><%= button_to "Contact Us", new_contact_path, :class => "btn btn-large", :method => :get %></p>
      </div>

      <div class="col-md-2 quick_links">
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'How It Works', how_it_works_path %></li>
          <li><%= link_to 'Benefits', benefits_path %></li>
        </ul>
      </div>
       
     <div class="col-md-2 quick_links">
        <ul>
          <li><a href="https://app.getelevate.com/login">Login</a></li>
          <li><a href="http://www.getelevate.com/blog">Blog</a></li>
          <li><a style="color:#A6001B !important; font-style: bold !important;" href="http://www.getelevate.com/contacts/new">Contact Us</a></li>
        </ul>
      </div>

      <div class="col-md-3 follow_us">
        <h2>Find Us Online</h2>
        <ul>
          <li><%= link_to image_tag("facebook.png"), 'https://www.facebook.com/getelevate' %></li>
          <li><%= link_to image_tag("twitter.png"), 'http://www.twitter.com/getelevate' %></li>
          <li><%= link_to image_tag("linkedin.png"), 'http://www.linkedin.com/groups?home=&gid=5025079&trk=anet_ug_hm' %></li>
          <li><%= link_to image_tag("google+.png"), 'https://plus.google.com/101056390946961113976/posts' %></li>
        </ul>
      </div>
    </div>
  </div>

<div class="container-fluid copyright_area">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 copyright">
      <p>@ Copyright 2014 Elevate Inc. All Rights Reserved</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
     <a href="https://heapanalytics.com/?utm_source=badge"><img style="height: 28px; width: 75px;" src="//heapanalytics.com/img/badge.png" alt="Heap - iOS and Web Analytics" /></a>
    </div>
  </div>
</div>

</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to image_tag('elevate_logo.png'), root_path, :class => 'brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'How It Works', how_it_works_path %></li>
        <li><%= link_to 'Benefits', benefits_path %></li>
        <li><a href="http://www.getelevate.com/blog">Blog</a><li>

        <li><a href="https://app.getelevate.com/login">Login</a></li> 
        <li><%= link_to 'Contact us', new_contact_path, {style: 'color:#A6001B !important; font-style: bold !important;'} %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/contact.html.erb
<% @title="Email Marketing Automation for Clients - Contact | Elevate" %>
<div class="platform_header">
	<h1>Contact Us</h1>
	<p>We would love the chance to help determine if we can help with your program goals.</p>
</div>

<div class="contact_area">
	<div class="container">
<%= form_for @contact do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :email %>:
  <%= f.text_field :email %><br />

  <%= f.label :company %>:
  <%= f.text_field :company %><br />

  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :head do %>
  <title>Email Marketing Automation for Clients - Homepage | Elevate</title>
<% end %>
<div class="hero_background">
  <div class="container-fluid">
    <div class="hero_area">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <h1>Maximize Revenue from Existing Clients</h1>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <h2>The Elevate Customer Engagement Platform
          </h2>
        </div>
      </div>


       <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= image_tag 'hero_no_bg_small.png' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <p>Elevate's next-generation email platform helps uncover up-sell, cross-sell and referral opportunities among your current clients.</p>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="container-fluid homepage_signup_background">
  <div class="col-md-8 col-md-offset-2 homepage_contact_form_area">
    <%= render 'layouts/messages' %>
      <%= form_for :contact, url: contacts_path, html: { class: "form-inline hp_contact_form "} do |f| %>
    
        <%= f.text_field :email, class: "form-control form_placeholder_text", placeholder: "Enter email address..." %>

        <span class="contact_button_homepage"><%= f.submit 'Request More Information', class: 'btn btn-large btn-primary'  %></span>
      <% end %>
  </div>
</div>


<div class="container-fluid">
  <div class="second_statement">
    <h2>A Few of Our Clients</h2>
    <hr>
     <p>
    
    </p>
    <%= image_tag 'clients3.png' %>
  </div>
</div>


<div class="container-fluid testimonial_background">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p><span class="quote_mark">"</span>With each Elevate email I send, it's exciting discovering how much revenue is hidden in my current client list.</span><span class="quote_mark">"</span>
      </p>
    </div>
  </div>

  <div class="row testimonial_attribute">
    <div class="col-md-6 col-md-offset-4">
       <p><%= image_tag 'chamandy.png' %> - Ian Chamandy, Blueprint Business Architecture</p>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="third_statement">
    <h2>A Bit About Elevate</h2>
  </div>

  <div class="row benefit_text">
    <div class="col-md-5 col-md-offset-1">
      <h3>Uncover Client Buying Interest</h3>
      <p>Discover upsell and cross-sell opportunities you never knew existed</p>
      <ul>
        <li><p>Learn client preferences across business units</p></li>
        <li><p>Understand which clients are ready to be contacted</p></li>
        <li><p>Make your content marketing data-driven</p></li>
      </ul>
    </div>

    <div class="col-md-5">
      <%= image_tag 'client_interest.png' %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <hr>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row benefit_text benefit_spacing">
    <div class="col-md-5 col-md-offset-1">
      <%= image_tag 'leads_sales.png' %>
    </div>

    <div class="col-md-5">
      <h3>Drive Leads Directly To Sales Teams</h3>
      <p>Give salespeople the data they need to uncover hidden revenue</p>
      <ul>
        <li><p>Tell sales teams which clients are ready to buy</p></li>
        <li><p>Figure out client interests across business divisions</p></li>
        <li><p>Build up a detailed interest profile on all your clients</p></li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <hr>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row benefit_text benefit_spacing">
    <div class="col-md-5 col-md-offset-1">
      <h3>Improve Your Client Email Experience</h3>
      <p>Have clients look forward to the content in your emails</p>
      <ul>
        <li><p>Segment your clients to ensure they only receive relevant info</p></li>
        <li><p>Understand which clients are ready to be contacted</p></li>
        <li><p>Create and execute mobile friendly programs in minutes</p></li>
      </ul>
    </div>

    <div class="col-md-5">
      <%= image_tag 'client_relations.png' %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <hr>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 benefit_text benefit_center crm_info">
      <h3>Fill Your CRM With Data Salespeople Will Actually Use</h3>
      <p>Provide your salespeople with relevant, timely client data</p>
      <div class="row benefit_text benefit_spacing">
        <div class="col-md-6 col-md-offset-3">
          <%= image_tag 'step7.png' %>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-md-offset-3 benefit_text benefit_center">
      <ul>
        <li><p>Tell sales teams which clients are ready to buy</p></li>
        <li><p>Figure out client interests across business divisions</p></li>
        <li><p>Build up a detailed interest profile on all your clients</p></li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid third_party_quote">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
     <h2>“Email is the #1 contact point for customers in all age categories.”<br />
      <span class="third_party_quoter">- Marketo</span></h2>
    </div>
  </div>
</div>


<div class="container-fluid home_page_contact">
   <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Schedule a demo to see how Elevate can work for you!</h2>
      <p>Let us show you how we can help you uncover buying interest and cross-selling opportunities</p>
    </div>
  </div>

   <div class="row">
    <div class="col-md-6 col-md-offset-3 homepage_button">
      <a href="/contacts/new"><button class="btn btn-primary btn-large"><span class="button_text">Show me what Elevate can do</span></button</a>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/pages/platform.html.erb
<% content_for :head do %>
  <title>Email Marketing Automation for Clients - Platform | Elevate</title>
<% end %>

<div class="container-fluid platform_overview">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>Elevate discovers cross-selling and up-selling opportunities</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Understand what your clients want to buy</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= image_tag 'how_it_works_3.png' %>
    </div>
  </div>
</div>



<div class="container-fluid third_party_quote">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
     <h2>“The probability of selling to an existing customer is 60–70%. <br />The probability of selling to a new prospect is 5-20%”<br />
      <span class="third_party_quoter">- Gartner</span></h2>
    </div>
  </div>
</div>

<!-- Three benefits -->
<div class="container-fluid programs_benefits">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2>Add Value to Your Client Communications</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-md-offset-1">
      <h3>Personalised</h3>
      <%= image_tag 'clipboard.png' %> <br/>
      <p>Improve your client relationships by customizing their marketing experience. Elevate automatically chooses content based on a client's preferences and buying interest to ensure relevance of your communications.
      </p>
    </div>

    <div class="col-md-4">
      <h3>Automated</h3>
      <%= image_tag 'mobile_optimized.png' %> <br/>
      <p>Take the work out of email marketing. Running a properly segmented, data-driven email program is nearly impossible without automation. Elevate automates 95% of all work involved to execute on a world-class email strategy.
      </p>
    </div>

    <div class="col-md-3">
      <h3>Data-Driven</h3>
      <%= image_tag 'track.png' %> <br/>
      <p>Take your email communications to the next level by creating rich profiles on all clients through their interactions with your emails. Drive qualified leads directly to your sales teams and flag upsell, cross-sell and retention opportunities.
      </p>
    </div>
  </div>
</div>
<!-- End Three benefits -->

<div class="container-fluid homepage_signup_background how_works_signup">
  <div class="col-md-8 col-md-offset-2 homepage_contact_form_area">
    <%= render 'layouts/messages' %>
      <%= form_for :contact, url: contacts_path, html: { class: "form-inline hp_contact_form "} do |f| %>
    
        <%= f.text_field :email, class: "form-control form_placeholder_text", placeholder: "Enter email address..." %>

        <span class="contact_button_homepage"><%= f.submit 'Request More Information', class: 'btn btn-large btn-primary'  %></span>
      <% end %>
  </div>
</div>

<div class="container-fluid faq_section">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Frequently Asked Questions</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <div class="faq_question">
        <h3>Why do you work with B2B companies?<h3>
        <p>Although we have some B2C clients, we believe that digest-style newsletters work best with B2B clients who see their vendors as a source of industry knowledge, not necessarily just a seller of products. We find that the sweet spot is any company who wants to be considered a thought leader to their clients in their industry of choice.  </p> 
      </div>

      <div class="faq_question">
        <h3>How is Elevate usually deployed?<h3>
        <p>Because it's email-based, segmentation of lists is important. We usually segment on a per-industry, per-account manager, or per product basis. Because the emails take minutes to product, Elevate makes it easy to execute on a segemented email strategy instead of blasting all of your clients the same messages regardless of what they care about.</p> 
      </div>

      <div class="faq_question">
        <h3>I already use marketing automation software. Why do I need you?<h3>
        <p>Good question. Most of our clients already use a type of marketing automation software. However, we find that it's mainly used to drive new leads. We don't do that. We care about nurturing current clients with valuable information in order to determine which client has interest in additional products or services from the company.</p> 
      </div>

      <div class="faq_question">
        <h3>Can I use this for my small business?<h3>
        <p>Although we usually only work with large enterprises, we do have some smaller clients who find they get the same quality of benefits. <a href="mailto:support@getelevate.com">Email us</a> and let's talk.</p>
      </div>

      <div class="faq_question">
        <h3>What type of support do you provide?<h3>
        <p>Because of the success with emails when client lists are properly segmented, we like to help with strategy as well as implementation. We also provide design support and can run entire programs for you. </p>
      </div>
    </div>

    <div class="col-md-5">
      <div class="faq_question">
        <h3>Why digest-style newsletters?<h3>
        <p>There are a few reasons why we focus on digest-style newsletters.</p>
          <ul>
            <li><p>Many of our B2B clients do not get enough website traffic to build rich data on their clients.</p></li>
            <li><p>Email is the #1 way to communicate with B2B clients among all categories.</p></li>
            <li><p>Being a thought leader on industry topics is important to most B2B companies</p></li>
            <li><p>Email is well understood as a strategy among B2B marketers.</li>
            <li><p>B2B companies generally have all the email addresses of their current clients.</p></li>
          </ul>
            <p>Essentially, email works in B2B. And Elevate does email in a way that adds value to the company-client relationship.</p>
      </div>

      <div class="faq_question">
        <h3>What kind of analytics do you provide?<h3>
        <p>We focus on delivering actionable sales data directly to your marketing and sales teams. In addition to building up a database of individual client preferences, we tell you which clients are reading any article that indicates buying interest in your products and services.</p> 
      </div>

      <div class="faq_question">
        <h3>Do you integrate with my CRM or marketing automation provider?<h3>
        <p>Yes. We integrate with popular enterprise CRMs such as Salesforce and Microsoft dynamics and we're currently working to integrate with Eloque and Marketo.</p> 
      </div>

      <div class="faq_question">
        <h3>How much does it cost?<h3>
        <p>It depends on how many segments you wish you run, how many recipients you have, the analytics and reporting you need, and the amount of customization required in your email templates. <a href="mailto:support@getelevate.com">Send us an email</a> and we would be happy to outline a cost for your program</p>
      </div>
    </div>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
       <hr />
    </div>
  </div>
</div>

<div class="container-fluid home_page_contact">
   <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Schedule a demo to see how Elevate can work for you!</h2>
      <p>Let us show you how we can help you uncover buying interest and cross-selling opportunities</p>
    </div>
  </div>

   <div class="row">
    <div class="col-md-6 col-md-offset-3 homepage_button">
      <a href="/contacts/new"><button class="btn btn-primary btn-large"><span class="button_text">Show me what Elevate can do</span></button</a>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/pages/program.html.erb
<% content_for :head do %>
  <title>Email Marketing Automation for Clients - Programs | Elevate</title>
<% end %>

<div class="container-fluid program_page_top">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h1>Digest-Style Newsletters Drive Customer Engagement </h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h3>Add value to your customer communications</h3>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-1 program_image">
      <%= image_tag 'program_image.png' %>
    </div>

    <div class="col-md-4 how_it_works_list">
      <h3>Reasons to love digest emails</h3>
      <hr>
      <ul>
        <li>Better targeted content</li>
        <li>Get more total engagement</li>
        <li>5X higher clickthrough rates</li>
        <li>Promotes thought leadership</li>
        <li>Create & send in minutes</li>
        <li>Easily segment your recipients</li>
        <li>Generate data on preferences</li>
        <li>Reduce email spam</li>
        <li>Re-use content assets</li>
        <li>Increase content sharing</li>
        <li>Populate CRM with useful info</li>
      </ul>
    </div>
  </div>
</div>


<div class="container-fluid homepage_signup_background how_works_signup">
  <div class="col-md-8 col-md-offset-2 homepage_contact_form_area">
    <%= render 'layouts/messages' %>
      <%= form_for :contact, url: contacts_path, html: { class: "form-inline hp_contact_form "} do |f| %>
    
        <%= f.text_field :email, class: "form-control form_placeholder_text", placeholder: "Enter email address..." %>

        <span class="contact_button_homepage"><%= f.submit 'Request More Information', class: 'btn btn-large btn-primary'  %></span>
      <% end %>
  </div>
</div>

<div class="container-fluid what_you_get">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Smart Content, Fast Creation, Deep Insights</h1>
      <h3>Segmented, digest-style newsletters allow companies to provide genuine value to their ongoing customer relationships. </h3>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <!-- Nav tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#smart_content" data-toggle="tab">Smart Content</a></li>
        <li><a href="#execution" data-toggle="tab">Simple to Use</a></li>
        <li><a href="#experience" data-toggle="tab">Better Customer Experience</a></li>
        <li><a href="#revenue" data-toggle="tab">Discover Hidden Revenue</a></li>
        
      </ul>
    </div>
  </div>
</div>

<!-- -->
<div class="tab-content">
  
<!-- Smart Content -->
  <div class="tab-pane active" id="smart_content">
    <div class="container-fluid program_content">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2>Content That Your Clients Want to Read</h2>
          <p>Elevate's content recommendation engine suggests content your clients will love.</p>
        </div>
      </div>

      <div class="row">
        <div class="col-md-8 col-md-offset-2 big_product_image_border">
          <%= image_tag 'smart_content.png' %>
        </div>
      </div>
    </div>  
  </div>


<!-- Start Furst -->
  <div class="tab-pane" id="execution">
    <div class="container-fluid big_product_image">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">  
          <h2>
            Create Digest-Style Newsletters In Minutes
          </h2>

          <p>Elevate automates 95% of the work involved to send high quality digest-style emails.</p>   
        </div>
      </div>
  
      <div class="row">
        <div class="col-md-8 col-md-offset-2 big_product_image_border">
          <%= image_tag 'product_big_ipad.png' %>
        </div>
      </div>
    </div>
  </div>

<!-- Start Second Tab -->
  <div class="tab-pane" id="revenue">
    <div class="container-fluid big_product_image">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2>
            Increase Retention, Up-Selling & Cross-Selling
          </h2>
          <p><b>Give your salespeople the info they need</b> </p> 

          <p>Your sales teams need to know what to talk to your clients about. Elevate automatically notifies them of clients who have expressed interest in company information or related products and services.</p> 
        </div>
      </div>
  
    <div class="row">
      <div class="col-md-8 col-md-offset-2 big_product_image_border">
        <%= image_tag 'client_reportcard.png' %>
      </div>
    </div>
  </div>
  </div>
  <!-- End Second Tab -->

  <!-- Start Third Tab -->
  <div class="tab-pane" id="experience">
    <div class="container-fluid big_product_image">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2>
            Improve Your Client Experience
          </h2>

          <p>Elevate makes it easy to understand and segment clients better to improve their relationship with you.</p> 
        </div>
      </div>
    </div>
  
    <div class="container-fluid good_email">
      <div class="row">
        <div class="col-md-6 col-md-offset-1">
          <h2>Send clients content they want to read</h2>
          <p>Elevate helps improve your understanding of client preferences, the content you use to engage them, and ultimately, your ability to upsell and cross-sell according to their needs.
          </p>

          <ul>
            <li><p>Understand client preferences to segment them properly</p></li>
            <li><p>Identify upsell and cross-sell opportunities</p></li>
            <li><p>Flag retention risk among current clients</p></li>
            <li><p>Deliver qualified leads directly to sales teams</p></li>
          </ul>
        </div>

        <div class="col-md-4">
          <%= image_tag 'good_email.png' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <hr>
        </div>
      </div
    </div>
  </div>
  <!-- end third tab -->


</div>
<!-- END ALL TABS-->



<div class="container-fluid program_checklist">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>We're in the Business of Customer Success</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <h3>Let Us Help You</h3>
      <p>Companies drive over 80% of business from existing clients. Make sure you maximize your experience and revenue potential with the people who have already trusted you with their business.
      </p><br />
      <%= image_tag 'clients_vertical.png' %>
    </div>

    <div class="col-md-5 checklist_right">
      <h3>All Programs Include</h3>

       <ul>
         <li><p>Detailed needs assessment</p></li>
         <li><p>Content & audience analysis</p></li>
         <li><p>Competitive overview and strategy</p></li>
         <li><p>Elevate 'White Glove' setup</p></li>
         <li><p>Marketing team Elevate accounts</p></li>
         <li><p>Access to Elevate's Content Curation module</p></li>
         <li><p>Intelligent email creation and analytics</p></li>
         <li><p>Analytics and Insights Dashboard</p></li>
         <li><p>24/7 phone and email customer service</p></li>
         <li><p>CRM & Marketing Automation integration</p></li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <hr>
    </div>
  </div>
</div>


<div class="container-fluid home_page_contact">
   <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Schedule a demo to see how Elevate can work for you!</h2>
      <p>Let us show you how we can help you uncover buying interest and cross-selling opportunities</p>
    </div>
  </div>

   <div class="row">
    <div class="col-md-6 col-md-offset-3 homepage_button">
      <a href="/contacts/new"><button class="btn btn-primary btn-large"><span class="button_text">Show me what Elevate can do</span></button</a>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>